### ISSUE TITLE
fixed-size search queues

### ISSUE THREAD

**Issue by tg-x** [pqwy/psq#1]
Just a heads up: I needed fixed-size search queues, so I just made [`fsq`](https://github.com/p2pcollab/ocaml-fsq) based on `psq`

**Comment by pqwy** [comment]
Glad it helped!

**Comment by pqwy** [comment]
@tg-x Ah, that's an LRU set. Here's an [LRU map](https://github.com/pqwy/lru) using the same idea.

**Comment by tg-x** [comment]
neat, exactly what i need, will have a look
